name: ddhome
version: 0.0.0
description: Maintain DNS records for a homelab setup
author: Alexey Kotlyarov <a@koterpillar.com>
maintainer: Alexey Kotlyarov <a@koterpillar.com>
license: GPL-3.0-or-later
language: GHC2024
default-extensions:
  - DefaultSignatures
  - DerivingVia
  - FunctionalDependencies
  - OverloadedStrings
  - RecordWildCards
  - DuplicateRecordFields
  - OverloadedRecordDot
dependencies:
  - aeson
  - aeson-jsonpath
  - base
  - bytestring
  - containers
  - extra
  - Glob
  - mtl
  - network-uri
  - safe-exceptions
  - text
  - vector
ghc-options:
  - -Wall
  - -Werror
  - -threaded
  - -optP-Wno-nonportable-include-path
library:
  source-dirs: src
tests:
  tests:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec
      - ddhome
    build-tools:
      - hspec-discover
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
executables:
  ddhome:
    main: Main.hs
    source-dirs: app
    dependencies:
      - ddhome
    ghc-options:
      - -rtsopts
      - -with-rtsopts=-N
