name: CI
on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: ./bin/install-dev
      - name: Lint
        run: ./bin/lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: ./bin/install-dev --no-lint
      - name: Test
        run: ./bin/test

  build:
    needs:
      - lint
      - test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        run: ./bin/install-dev --no-lint
      - name: Compile
        run: cargo +stable build --release
      - name: Move executable
        run: cp target/release/ddhome ./ddhome-$(uname)-$(uname -m)
      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: executable-${{ runner.os }}-${{ runner.arch }}
          path: ddhome-*

  publish:
    needs:
      - build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
      - name: Install dependencies
        run: ./bin/install-dev --no-lint
      - name: Download executables
        uses: actions/download-artifact@v8
        with:
          pattern: 'executable-*'
          merge-multiple: true
          path: ./executables
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx \
            --package semantic-release@25 \
            semantic-release
